### ISSUE TITLE
Connecting RUM and Logs to Trace in Swift

### ISSUE THREAD

**Issue by Alexander-techIOS** [DataDog/dd-sdk-ios#424]
### Connect RUM and Logs to Trace in Swift

```
Datadog.initialize(
            appContext: .init(),
            configuration: Datadog.Configuration
                .builderUsing(
                    rumApplicationID: "<rumID>",
                    clientToken: "<clientToken>",
                    environment: "\(server)"
                )
                .trackUIKitActions(true)
                .trackUIKitRUMViews(using: DefaultUIKitRUMViewsPredicate())
                .track(firstPartyHosts: ["\(ServerConfig.standard.firstPartyHost)"])
                .set(serviceName: "ios - \(server)")
                .build()
        )

        Datadog.verbosityLevel = .debug
        Global.sharedTracer = Tracer.initialize(configuration: Tracer.Configuration(serviceName: "ios - \(server)",
                                                                                    sendNetworkInfo: true,
                                                                                    bundleWithRUM: true,
                                                                                    globalTags: nil)
        )

        let session = URLSession(configuration: .default, delegate: DDURLSessionDelegate(), delegateQueue: nil)
        NetquityEngine.standard.initializeURLSession(session)

        Global.rum = RUMMonitor.initialize()
        
        self.logger = Logger.builder
            .sendNetworkInfo(true)
            .sendLogsToDatadog(true)
            .bundleWithRUM(true)
            .bundleWithTrace(true)
            .printLogsToConsole(true, usingFormat: .shortWith(prefix: "[DEBUG LOGGER] "))
            .set(loggerName: "ios - \(server)")
            .build()
    }
```

The above is the initialization of the Tracker class. On datadog we get the traces, we get logs and we get RUM events but none of them link to each other, ie. in traces we cannot see associated logs and in logs or RUM we cannot see any traces.

The docs mention that we inject the `trace_id` and `span_id` into the attributes of the logs and make sure the logs are encoded as JSON. I am assuming it is JSON by default since didn't change that and when making a network request we start a span:

`let span = Global.sharedTracer.startSpan(operationName: url.path)`

We inject the headers:

```
       let headersWritter = HTTPHeadersWriter()
        Global.sharedTracer.inject(spanContext: span.context, writer: headersWritter)
        
        for (headerField, value) in headersWritter.tracePropagationHTTPHeaders {
            request.addValue(value, forHTTPHeaderField: headerField)
        }
```

In the network callback we attach the `span_id` and `trace_id` for `span` in the error log event attributes but nothing traces for Logs and no logs for traces in the APM section. Another thing, since we are using `DDURLSessionDelegate` another span is created to report when an error occurs, this results in 2 traces one for the manual span before the network request and assuming one created by `DDURLSessionDelegate` but neither of them link to a log. Not even the manual one. 

An example of adding `span_id` and `trace_id` to a log event:

```
let span = Global.sharedTracer.startSpan(operationName: url.path)

let task = session.dataTask(with: request) { (data, response, error) in 
       // Handle network error
      if let httpResponse = response as? HTTPURLResponse {
            if httpResponse.statusCode > 300 {
                     let addInfo = ["trace_id": headersWritter.tracePropagationHTTPHeaders["x-datadog-trace-id]!,
                                             "span_id": headersWritter.tracePropagationHTTPHeaders["x-datadog-parent-id"]!]
                     logger.error("Error \(httpResponse.statusCode)", attributes: addInfo)
            }
      }
}

task.resume()
```

The resulting event does not link to a trace and the trace doesn't pick up any logs.
Please could you point me in the correct direction to link them or am I just looking at the wrong interface on DD?

**Comment by ncreated** [comment]
Hello @Alexander-techIOS 👋 , thanks for reaching us - happy to see you exploring our integrations.

All our integrations are enabled by default and we tune them up to give best results with no additional setup. Thus, you should get good defaults with only using this minimal initialization (following code uses [`1.4.1` release](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.4.1)):
```swift
import Datadog

Datadog.initialize(
    appContext: .init(),
    configuration: Datadog.Configuration
        .builderUsing(
            rumApplicationID: "<rum-app-id>",
            clientToken: "<client-token>",
            environment: "<env>"
        )
        .trackUIKitRUMViews()
        .trackUIKitActions()
        .track(firstPartyHosts: ["your-host.com"])
        .set(serviceName: "app-name")
        .build()
)

// initialize APM Tracer:
Global.sharedTracer = Tracer.initialize(configuration: .init())

// initialize RUM:
Global.rum = RUMMonitor.initialize()

// initialize Logger:
logger = Logger.builder.build()

// instrument URLSession:
session = URLSession(
   configuration: ...,
   delegate: DDURLSessionDelegate(),
   delegateQueue: ...
)
```
_Note: I'm not using `bundleWith*` options, as all of them default to `true`._

With this minimal setup, Datadog will monitor your RUM Views (`UIViewControllers`), RUM Actions (taps on `UIControl` elements) and RUM Resources (`URLRequests` sent through the `session`). All our integrations are enabled by default and do not require any additional setup on your side (like injecting `span_id` or `trace_id`).

Here's the list of integrations, followed by its detailed description:
* 1/ we generate and link APM spans for all `XHR` RUM Resources,
* 2/ we link logs sent through the `logger` with the active RUM View,
* 3/ we link APM traces sent through `Global.sharedTracer` with the active RUM View,
* 4/ we link logs sent with `span.log()` with the APM trace,
* 5/ we link logs sent through `logger` with the active APM span.

### 1. RUM Resources <> APM connection.

This integration is automatic. With the above code snippet, whenever an `XHR` RUM Resource is sent, we will generate corresponding APM trace for it. You can find it in RUM View, on the "Traces" tab, next to the "Resources" tab:

<img width="858" alt="Screenshot 2021-03-03 at 09 50 25" src="https://user-images.githubusercontent.com/2358722/109782304-0677da80-7c09-11eb-8139-c4448a7ae93d.png">

_Note: `XHR` resource kind is set for `URLRequests` which use POST, PUT and DELETE methods._

### 2. Log <> RUM View connection.

This integration links a log the the active RUM View. In the initialization snippet I'm using default `.trackUIKitRUMViews()` option meaning that RUM View will be started for every custom view controller. Sending a log from view controller:
```swift
class ViewController2: UIViewController {
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        logger.info("ViewController2.viewDidAppear()")
   }
}
```
will make it appear under "Logs" tab in the RUM View:

<img width="824" alt="log to rum" src="https://user-images.githubusercontent.com/2358722/109788130-40e47600-7c0f-11eb-88e5-7fccd1647f8a.png">

_Note: RUM View starts with view controller's `viewDidAppear(_:)` that's why it will aggregate logs send after it._

### 3. APM Trace <> RUM View connection.

Similar to Log <> RUM View connection, all APM traces created with `Global.sharedTracer` should be linked to the active RUM View and appear on the "Traces" tab. Unfortunately, we're having an issue with this integration and we're working on the 🐞 fix.

### 4. Explicit Log <> APM Trace connection using `span.log()`.

There are two ways to link logs with APM traces. First is by using explicit `span.log()` API:
```swift
func bar() {
   let span = Global.sharedTracer.startSpan(operationName: "bar()")
   // ...
   span.log(fields: [OTLogFields.message: "log from `bar()`"])
   // ...
   span.finish()
}
```
This will send a log (_"log from `bar()`"_) associated with the `span`. You can see it in APM trace view, under "Logs" tab:

<img width="1085" alt="Screenshot 2021-03-03 at 11 07 38" src="https://user-images.githubusercontent.com/2358722/109789948-257a6a80-7c11-11eb-9737-e31d84e609ba.png">

_Note: the `100ms` bar marks the precise moment at which the log was created._

### 5. Implicit Log <> APM Trace connection using `span.setActive()` API.

The second way of linking logs with APM traces is by using active span concept. In contrast to `span.log()` API, this approach doesn't require an explicit reference to the `span`. If an active span exists in the current execution context (on the current thread), all logs sent through the `logger` will be linked to it:
```swift
// start span and set it active with `.setActive()`
Global.sharedTracer.startSpan(operationName: "foo()").setActive()

foo()

// finish the active span
Global.sharedTracer.activeSpan?.finish()

func foo() {
   // ...
   logger.info("log from `foo()`")
   // ...
}
```

The result of this connection wil be exactly the same as when using `span.log()` API.

---

@Alexander-techIOS note that all that I discussed comes from the default setup we provide in `dd-sdk-ios`. If you'd like to **disable** some of this automatic integrations you can use following methods respectively:
* `Logger.builder.bundleWithRUM(false).build()` - to disable Log <> RUM View integration (2),
* `Logger.builder.bundleWithTrace(false).build()` - to disable implicit Log <> APM integration (5),
* `Tracer.initialize(configuration: .init(bundleWithRUM: false))` - to disable APM Trace <> RUM View integration (3).

I hope you will find this useful, let us know if it works for you 🙂.

**Comment by Alexander-techIOS** [comment]
Thanks for the response @ncreated I will give it a shot.

**Comment by Alexander-techIOS** [comment]
@ncreated I would like to check is the only way to add additional info regarding an XHR request, be attached as a separate logger submission? Ie if there was a network request error, I would like to see the data sent and the headers for the request likewise the response data and the response header. Currently, I have implemented a separate logger call to log this additional data, but APM traces results in 2 spans, 1 sent via DDURLSessionDelegate (this is an assumption) and 1 sent manually myself and the manual span displays the linked log with the additional data and the manual span isn't the same as the error one, this makes it almost like a separate event. 

![Screen Shot 2021-03-05 at 9 08 05 AM](https://user-images.githubusercontent.com/52926937/110126321-4ddda280-7d92-11eb-9895-014c404fc855.png)
![Screen Shot 2021-03-05 at 9 08 47 AM](https://user-images.githubusercontent.com/52926937/110126411-65b52680-7d92-11eb-9a16-c9f60826ed14.png)
![Screen Shot 2021-03-05 at 9 09 13 AM](https://user-images.githubusercontent.com/52926937/110126471-75346f80-7d92-11eb-9b57-6ed655a8f4e7.png)

The second image is the manually sent APM, the attached log (sent by logger) has the additional info, but it is not an error. 
The third image is the auto sent APM, no related logs but 1 error, and that error has no information except `error: true`

Is there a way to add more info to the XHR APM span?

**Comment by ncreated** [comment]
@Alexander-techIOS regarding adding more information to automatically collected APM Spans, this is something that we will be working on shortly. Indeed, right now we don't provide any control over `Spans` produced for intercepted network requests. Feel free to start a separate GH Issue with this feature request or we will just inform you here once this is done.

**Comment by nicolas-vivot** [comment]
Hi there,

We are also experiencing a similar issue that the one described here.
We implemented the default auto instrumentation configuration, we also added the manual instrumentation code from your official blog/guide and are still facing the following issue:

Any GET request performed is reported as a Trace on Datadog, but this trace information (trace_id & span_id) are never propagated to the request headers, and therefore the backend execution (also instrumented with datadog java agent) is reported as a different trace, with no link to the supposed parent trace.

Seems like all of this is because you propagate the trace information only for resources tags as XHR on your library.
So the question is: why GET is out of the list of XHR resources ? Or why do you tight the resource type with the tracing propagation ?

Propagation should never be dependent on anything: you have a trace, you have a request : you propagate it, that's all.

Can we know when you're going to fix that ?

**Comment by ncreated** [comment]
> Seems like all of this is because you propagate the trace information only for resources tagged as XHR on your library.
> So the question is: why GET is out of the list of XHR resources ? Or why do you tight the resource type with the tracing propagation mechanism ? (if that's really what's happening here)
> 
> Propagation should never be dependent on anything: you have a trace, you have a request : you propagate it, that's all.

Hello @nicolas-vivot 👋. Trace info injection does not depend on the resource type (in fact, the resource type is determined later - when the MIME type is received upon response completion). Instead, `trace_id` and `span_id` are injected to all "first party" requests (of any kind and any method). 

First party requests must be configured in `trackURLSession(firstPartyHosts:)` API when initializing the SDK (see: [RUM configuration docs](https://docs.datadoghq.com/real_user_monitoring/ios/advanced_configuration/#rum-configuration)). We use this concept to let the user decide if the tracing info should be propagated to given url or not.

Could you check out if the Datadog-insturmented host that you are targeting is listed in the `firstPartyHosts:`?

**Comment by nicolas-vivot** [comment]
Hi @ncreated 

You are right, i could check the trace propagation. I'm using Traefik in between the client and the target service and the datadog trace_id and span_id appear on Traefik access logs.

Yes the datadog-instrumented host i'm targeting is listed in the `firstPartyHosts:` option.

Here is the initialization code for the datadog part:

![image](https://user-images.githubusercontent.com/79290619/127929377-ed3dd0d9-1237-4c95-953a-f7f7a220a31c.png)

We also added some manual instrumentation as @AXR-Tech did.

All GET calls made to the first party hosts are visible on the APM as a single trace/span from the Mobile application. The backend part is visible as a second and distinct trace, with no link between those two. That's the problem.

I supposed this is due to the XHR type because:

- none of these GET are flagged as XHR resource on the RUM and that's the only difference i can spot between the iOS SDK behavior and the Node JS Web libraries.
- you stated this in your previous answer:
`This integration is automatic. With the above code snippet, whenever an XHR RUM Resource is sent, we will generate corresponding APM trace for it.`

I guess what we observe is the result of mixing the datadog auto instrumentation with first party hosts and the manual instrumentation:
- for all POST & PUT calls, we get two traces from the Mobile application layer reported on the APM/RUM: one might be the manual instrumentation one, the other one the auto instrumentation one that is correctly linked & shown with the backend.
- for all GET calls, we get only one trace from the Mobile application layer reported on the APM/RUM : the manual instrumentation one.

If we remove the manual instrumentation - that should not be necessary right? - then we would have 0 trace for all GET requests made to our first party hosts. This is the problem.
Do you have any idea about the potential reason ?

**Comment by ncreated** [comment]
@nicolas-vivot thanks for more context 🙂. Your observation seems correct, I forgot to mention that in https://github.com/DataDog/dd-sdk-ios/pull/524 we improved our classification of `XHR` requests. `XHR` becomes a default choice, so you should see it appearing also for `GET` requests. However, this change is not included in `1.6.0` release and you may need to try `1.7.0-beta2` to enable this.

When it comes to mixing auto and manual instrumentations - is there a reason why you're doing this? That would make sense for `URLSession` instances which are not instrumented with `DDURLSessionDelegate` (hence: auto instrumentation won't work for them), but normally RUM auto instrumentation should do the job for you 🙂.

**Comment by nicolas-vivot** [comment]
@ncreated 

No reason for the manual instrumentation but to find why we had missing traces.

I'll ask the iOS devs to upgrade to the beta version you mentioned and remove the manual instrumentation. 

Thank you for your quick feedback.
