### ISSUE TITLE
SDK doesn't build on Xcode running on M1 based Mac

### ISSUE THREAD

**Issue by ahmdmhasn** [DataDog/dd-sdk-ios#731]
### The issue
`Module 'Datadog' was created for incompatible target arm64-apple-ios11.0` when building on MacOS M1 based chip. As a workaround, we are running Xcode on **Rosetta** to be able to use the SDK inside the project.

#### Datadog SDK version:
`1.8.0`

#### Last working Datadog SDK version:
Using Intel based Mac || Using Rosetta 
 
#### Dependency Manager:
Cocoapods

#### Xcode version:
Version 13.2 (13C90)

#### Swift version:
Swift 5.5

#### Deployment Target:
iOS 11.0
<img width="686" alt="Screen Shot 2022-02-21 at 2 30 14 PM" src="https://user-images.githubusercontent.com/45182214/154958639-9dcddd91-698c-4fc2-ba66-c5ce640ecdf5.png">

**Comment by 23prash** [comment]
Hello,
Do you plan to address this issue soon? would be great if we can get an idea of timeline?

**Comment by ARamy23** [comment]
Been running into this lately as well, would be nice to know if someone is aware of this

**Comment by ncreated** [comment]
Hello 👋. I finally got access to M1 machine and I've been looking into this. However, I need more context to reproduce it and to move forward. I tried with vanilla project on M1 Mac and it worked with no issue, so I wonder where is the difference 🤔.

What I've tried:
* 1/ Create app project with Xcode 13.2.1; deployment target iOS 11.0;
* 2/ Add following `Podfile`:
```ruby
platform :ios, '11.0'

target 'GHIssue731' do
  use_frameworks!

  pod 'DatadogSDK'
  pod 'DatadogSDKCrashReporting'
end
```
* 3/ Run `arch -x86_64 pod update` (in M1 shell):

![Screenshot 2022-02-15 at 19 36 36](https://user-images.githubusercontent.com/2358722/154131640-02d0d4a9-0716-42ef-83cc-4475509a3fb1.png)

* 4/ Build & run `Debug` configuration on Simulator - works fine;
* 5/ Build & run `Debug` configuration on real iPhone - works fine.

Also, here are the key Build Settings I've been using (all set to default):

![Screenshot 2022-02-15 at 19 32 38](https://user-images.githubusercontent.com/2358722/154132163-68d748d1-ab5e-4a08-805a-14ba7ee40ba7.png)

I'd really appreciate if someone can provide steps to reproduce 🙏 or minimal setup for a fresh project. Likely we need [this patch](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io/63955114#63955114) (it also includes workaround with `EXCLUDED_ARCHS`), but I can't verify it without facing this problem first.

**Comment by ARamy23** [comment]
@ncreated Hi there! I think the difference between the project and urs is that we are not using the SDKCrashReporting

however, we do use `excluded_archs` set to `arm64`, and Datadog is not compiling with the same error mentioned by the OP `Module 'Datadog' was created for incompatible target arm64-apple-ios12.0` (but with ios12.0)

**Comment by ncreated** [comment]
@ARamy23 thanks for details 👌. We also have two more questions:
* First, why do you need to exclude `arm64` at all? The fresh project I made builds ok both for Simulator and for a real device - in which case is `arm64` in `EXCLUDED_ARCHS` leveraged/required in your workflow?
* Second, do you get this error when compiling for iOS Simulator or for physical device?

**Comment by ARamy23** [comment]
@ncreated Hi again, 

1. as for arm64, that was a try on my end that was just registered on git, but that's not the norm here,
so I think there is more to it
2. as for now, I can't test this on a physical device yet


However there is a useful input, which ticking "Open using Rosetta" in Xcode doesn't trigger the same behavior in the compilation
![CleanShot 2022-02-16 at 20 21 26@2x](https://user-images.githubusercontent.com/31904352/154330600-99a5089b-bc57-45ad-90c8-6ce3478d2eee.png)

**Comment by ncreated** [comment]
Hello @ahmdmhasn 👋. I didn't have a chance to try on M1 machine recently. However, I'm still wondering why you need the `arm64` option in `EXCLUDED_ARCHS`? I assume you have it, because everything worked smooth for me in vanilla app project built on M1. To my understanding, removing it should fix the problem - but I need to know if it's possible for you to do so and/or why not.

**Comment by ahmdmhasn** [comment]
Thanks @ncreated for quick response 🙏
I've removed any traces of `EXCLUDED_ARCHS` in the modules but it doesn't seem to fix the issue. 
Is there any solution for the SDK to support ARM chips? since the issue only appear with DataDog?

**Comment by ncreated** [comment]
Thanks for checking this out @ahmdmhasn 👍. If the issue persists in your project, but it worked for me in a fresh new project I did in https://github.com/DataDog/dd-sdk-ios/issues/731#issuecomment-1040692510, I don't think this is necessary a problem with Datadog iOS SDK. Looking at our [`DatadogSDK.podspec`](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogSDK.podspec) I can't see anything that would limit/alter the arch slices produced on your end in `pod install`.

Could you please try reproducing it in a fresh new project following my steps from https://github.com/DataDog/dd-sdk-ios/issues/731#issuecomment-1040692510? We need a minimal reproduction steps for the project setup to move further on this issue, ideally:
* the `Podfile`;
* `pod install` output;
* dump of "Architecture" Build Settings;
* does the issue appear when building for Simulator or Device?
* which configuration (Debug / Release) does cause the issue?

Meantime, you may also try the `post_install` patch proposed in [this SO answer](https://stackoverflow.com/a/63955114) (normally, I'd try it first on my end, but I don't know the reproduction steps for this issue). Sorry it's taking time, I don't have M1 machine at my constant disposal.

**Comment by ahmdmhasn** [comment]
Hello @ncreated.. After deep investigation in the issue, It seems to be due to [Cocoapods-Binary](https://github.com/leavez/cocoapods-binary) Check this [line](https://github.com/leavez/cocoapods-binary/blob/b22bd948a3168a323b1ffa61095468f2c91c1cee/lib/cocoapods-binary/rome/build_framework.rb#L33) which forces `ARCHS=x86_64` architecture. 

So I think more work needed from your side.. Thanks for your efforts 🙏
